config/routes.rb
Rails.application.routes.draw do
  resources :alunos do
    member do
      get :responder_questoes
      post :salvar_respostas
    end
  end

  resources :questaos
  resources :casas do
    collection do
      get :atribuicao_pontual_especial # Página com a lista de casas
      post :adicionar_pontos # Atribuição dos pontos
    end
  end

  # Rota padrão
  root "casas#index"
end

app/models/casa.rb
class Casa < ApplicationRecord
  has_many :alunos
end

app/controllers/casas_controller.rb
class CasasController < ApplicationController
  before_action :set_casa, only: %i[show edit update destroy] # Removido o :adicionar_pontos

  # GET /casas or /casas.json
  def index
    @casas = Casa.all
  end

  # GET /casas/1 or /casas/1.json
  def show
  end

  def alunosPorCasa
    @alunosPorCasa = Aluno.all
  end

  # GET /casas/new
  def new
    @casa = Casa.new
  end

  # GET /casas/1/edit
  def edit
  end

  # POST /casas or /casas.json
  def create
    @casa = Casa.new(casa_params)

    respond_to do |format|
      if @casa.save
        format.html { redirect_to @casa, notice: "Casa criada com sucesso." }
        format.json { render :show, status: :created, location: @casa }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @casa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /casas/1 or /casas/1.json
  def update
    respond_to do |format|
      if @casa.update(casa_params)
        format.html { redirect_to @casa, notice: "Casa atualizada com sucesso." }
        format.json { render :show, status: :ok, location: @casa }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @casa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /casas/1 or /casas/1.json
  def destroy
    @casa.destroy!

    respond_to do |format|
      format.html { redirect_to casas_path, status: :see_other, notice: "Casa excluída com sucesso." }
      format.json { head :no_content }
    end
  end

  def atribuicao_pontual_especial
    @casas = Casa.all || []
  end


  # POST /casas/adicionar_pontos
def adicionar_pontos
  if params[:casa_id].present?
    @casa = Casa.find_by(id: params[:casa_id])

    if @casa
      pontos = params[:pontos].to_i

      if pontos != 0
        @casa.increment!(:pontos, pontos)
        acao = pontos.positive? ? "adicionados" : "removidos"
        redirect_to atribuicao_pontual_especial_casas_path, notice: "#{pontos.abs} pontos #{acao} com sucesso da casa #{@casa.nome}!"
      else
        redirect_to atribuicao_pontual_especial_casas_path, alert: "Por favor, insira um valor de pontos diferente de zero."
      end
    else
      redirect_to atribuicao_pontual_especial_casas_path, alert: "Casa não encontrada."
    end
  else
    redirect_to atribuicao_pontual_especial_casas_path, alert: "Por favor, selecione uma casa."
  end
end




  private

    # Use callbacks to share common setup or constraints between actions.
    def set_casa
      @casa = Casa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def casa_params
      params.require(:casa).permit(:nome, :pontos)
    end
end

app/helpers/casas_helper.rb
module CasasHelper
end

app/views/casas/_casa.html.erb
<%= stylesheet_link_tag "casas", media: "all", "data-turbo-track": "reload" %>
<div class="containaer">

    <%@alunosPorCasa = Aluno.all%>

    <table id="questoes-table" class="table table-striped"
       data-pagination="true"
       data-page-size="10"
       data-search="true"
       data-show-columns="true"
       data-pagination-parts='["pageSize", "pageList"]'
       data-toggle="table"
       data-search-placeholder="Pesquisar...">
  <thead>
    <tr>
      <th data-field="enunciado" data-sortable="true">Aluno (a) </th>
      <th data-field="status" data-sortable="false">Turma</th>
    </tr>
  </thead>
  <tbody>
    <% @alunosPorCasa.each do |aluno| %>
      <tr>
        <%if aluno.casa_id == casa.id%>
          <td><%= aluno.nome %></td>
          <td><%= aluno.turma %></td>
        <%end%>

    </tr>
    <% end %>
  </tbody>
</table>






</div>

app/views/casas/_form.html.erb
<%= form_with(model: casa) do |form| %>
  <% if casa.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(casa.errors.count, "error") %> prohibited this casa from being saved:</h2>

      <ul>
        <% casa.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :pontos, style: "display: block" %>
    <%= form.number_field :pontos %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/casas/atribuicao_pontual_especial.html.erb
<%= stylesheet_link_tag "casas", media: "all", "data-turbo-track": "reload" %>

<div class="container mt-4">
  <h1 class="text-center mb-4">Atribuição de Pontos às Casas</h1>

  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% elsif alert %>
    <div class="alert alert-danger" role="alert">
      <%= alert %>
    </div>
  <% end %>

  <%= form_with url: adicionar_pontos_casas_path, method: :post, class: "card p-4 shadow" do %>
    <div class="mb-3">
      <label for="casa_id" class="form-label">Selecione a Casa:</label>
      <%= select_tag :casa_id, options_from_collection_for_select(@casas, :id, :nome), prompt: "Escolha uma casa", class: "form-select" %>
    </div>

    <div class="mb-3">
      <label for="pontos" class="form-label">Quantidade de Pontos (use valores negativos para subtrair):</label>
      <%= number_field_tag :pontos, nil, class: "form-control" %>
    </div>

    <div class="d-grid">
      <%= submit_tag "Adicionar/Remover Pontos", class: "btn btn-success btn-sm w-25 mx-auto" %>
    </div>
  <% end %>

  <div class="text-center mt-4">
    <%= link_to "Acompanhar Placar", casas_path, class: "btn btn-primary", target: "_blank" %>
  </div>
</div>

app/views/casas/edit.html.erb
<% content_for :title, "Editing casa" %>

<h1>Editing casa</h1>

<%= render "form", casa: @casa %>

<br>

<div>
  <%#= link_to "Show this casa", @casa %> |
  <%#= link_to "Back to casas", casas_path %>
</div>

app/views/casas/index.html.erb
<p style="color: green"><%= notice %></p>

<%= stylesheet_link_tag "casas", media: "all", "data-turbo-track": "reload" %>
<% require 'json' %>

<!-- Estilos -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.21.1/bootstrap-table.min.css" rel="stylesheet">

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.21.1/bootstrap-table.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<% content_for :title, "Casas" %>

<h1>CASAS</h1>

<div class="container mt-5">
  <div class="row">
    <% @casas.each do |casa| %>
      <div class="col-md-4">
        <div class="card text-center">
          <div class="card-body">
            <h5 class="card-title"><%= casa.nome %></h5>
            <p class="card-text"><%= casa.pontos %></p>

            <% imagem = case casa.nome.downcase %>
              <% when "css" then "css.png" %>
              <% when "html" then "html.png" %>
              <% when "javascript" then "js.png" %>
            <% end %>

            <% if imagem.present? %>
              <img src="<%= asset_path(imagem) %>" alt="<%= casa.nome %>" class="img-fluid mb-3 casa-imagem">
            <% end %>

            <%= link_to "Ver Casa", casa, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%#= link_to "Nova Casa", new_casa_path, class: "btn btn-success mt-3" %>

app/views/casas/new.html.erb
<% content_for :title, "New casa" %>

<h1>New casa</h1>

<%= render "form", casa: @casa %>

<br>

<div>
  <%= link_to "Back to casas", casas_path %>
</div>

app/views/casas/show.html.erb
<%= stylesheet_link_tag "casas", media: "all", "data-turbo-track": "reload" %>

<%= render @casa %>

<div>
  <%#= link_to "Edit this casa", edit_casa_path(@casa) %>
  <%= link_to "Voltar", casas_path %>

  <%#= button_to "Destroy this casa", @casa, method: :delete %>
</div>